// Code generated by protoc-gen-go.
// source: system.proto
// DO NOT EDIT!

/*
Package system is a generated protocol buffer package.

It is generated from these files:
	system.proto

It has these top-level messages:
	MsgAuthClient
	MsgAuthServer
	MsgAuthEcho
*/
package system

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type MsgAuthClient struct {
	Label            *string                      `protobuf:"bytes,1,req,name=label" json:"label,omitempty"`
	Type             *int32                       `protobuf:"varint,2,opt,name=type" json:"type,omitempty"`
	Text             *string                      `protobuf:"bytes,3,opt,name=text" json:"text,omitempty"`
	Reps             []int64                      `protobuf:"varint,4,rep,name=reps" json:"reps,omitempty"`
	Optionalgroup    *MsgAuthClient_OptionalGroup `protobuf:"group,5,opt,name=OptionalGroup,json=optionalgroup" json:"optionalgroup,omitempty"`
	XXX_unrecognized []byte                       `json:"-"`
}

func (m *MsgAuthClient) Reset()                    { *m = MsgAuthClient{} }
func (m *MsgAuthClient) String() string            { return proto.CompactTextString(m) }
func (*MsgAuthClient) ProtoMessage()               {}
func (*MsgAuthClient) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *MsgAuthClient) GetLabel() string {
	if m != nil && m.Label != nil {
		return *m.Label
	}
	return ""
}

func (m *MsgAuthClient) GetType() int32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *MsgAuthClient) GetText() string {
	if m != nil && m.Text != nil {
		return *m.Text
	}
	return ""
}

func (m *MsgAuthClient) GetReps() []int64 {
	if m != nil {
		return m.Reps
	}
	return nil
}

func (m *MsgAuthClient) GetOptionalgroup() *MsgAuthClient_OptionalGroup {
	if m != nil {
		return m.Optionalgroup
	}
	return nil
}

type MsgAuthClient_OptionalGroup struct {
	RequiredField    *string `protobuf:"bytes,5,req,name=RequiredField,json=requiredField" json:"RequiredField,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MsgAuthClient_OptionalGroup) Reset()                    { *m = MsgAuthClient_OptionalGroup{} }
func (m *MsgAuthClient_OptionalGroup) String() string            { return proto.CompactTextString(m) }
func (*MsgAuthClient_OptionalGroup) ProtoMessage()               {}
func (*MsgAuthClient_OptionalGroup) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

func (m *MsgAuthClient_OptionalGroup) GetRequiredField() string {
	if m != nil && m.RequiredField != nil {
		return *m.RequiredField
	}
	return ""
}

type MsgAuthServer struct {
	Label            *string                      `protobuf:"bytes,1,req,name=label" json:"label,omitempty"`
	Type             *int32                       `protobuf:"varint,2,opt,name=type" json:"type,omitempty"`
	Text             *string                      `protobuf:"bytes,3,opt,name=text" json:"text,omitempty"`
	Reps             []int64                      `protobuf:"varint,4,rep,name=reps" json:"reps,omitempty"`
	Optionalgroup    *MsgAuthServer_OptionalGroup `protobuf:"group,5,opt,name=OptionalGroup,json=optionalgroup" json:"optionalgroup,omitempty"`
	XXX_unrecognized []byte                       `json:"-"`
}

func (m *MsgAuthServer) Reset()                    { *m = MsgAuthServer{} }
func (m *MsgAuthServer) String() string            { return proto.CompactTextString(m) }
func (*MsgAuthServer) ProtoMessage()               {}
func (*MsgAuthServer) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *MsgAuthServer) GetLabel() string {
	if m != nil && m.Label != nil {
		return *m.Label
	}
	return ""
}

func (m *MsgAuthServer) GetType() int32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *MsgAuthServer) GetText() string {
	if m != nil && m.Text != nil {
		return *m.Text
	}
	return ""
}

func (m *MsgAuthServer) GetReps() []int64 {
	if m != nil {
		return m.Reps
	}
	return nil
}

func (m *MsgAuthServer) GetOptionalgroup() *MsgAuthServer_OptionalGroup {
	if m != nil {
		return m.Optionalgroup
	}
	return nil
}

type MsgAuthServer_OptionalGroup struct {
	RequiredField    *string `protobuf:"bytes,5,req,name=RequiredField,json=requiredField" json:"RequiredField,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MsgAuthServer_OptionalGroup) Reset()                    { *m = MsgAuthServer_OptionalGroup{} }
func (m *MsgAuthServer_OptionalGroup) String() string            { return proto.CompactTextString(m) }
func (*MsgAuthServer_OptionalGroup) ProtoMessage()               {}
func (*MsgAuthServer_OptionalGroup) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 0} }

func (m *MsgAuthServer_OptionalGroup) GetRequiredField() string {
	if m != nil && m.RequiredField != nil {
		return *m.RequiredField
	}
	return ""
}

type MsgAuthEcho struct {
	Label            *string                    `protobuf:"bytes,1,req,name=label" json:"label,omitempty"`
	Type             *int32                     `protobuf:"varint,2,opt,name=type" json:"type,omitempty"`
	Text             *string                    `protobuf:"bytes,3,opt,name=text" json:"text,omitempty"`
	Reps             []int64                    `protobuf:"varint,4,rep,name=reps" json:"reps,omitempty"`
	Optionalgroup    *MsgAuthEcho_OptionalGroup `protobuf:"group,5,opt,name=OptionalGroup,json=optionalgroup" json:"optionalgroup,omitempty"`
	XXX_unrecognized []byte                     `json:"-"`
}

func (m *MsgAuthEcho) Reset()                    { *m = MsgAuthEcho{} }
func (m *MsgAuthEcho) String() string            { return proto.CompactTextString(m) }
func (*MsgAuthEcho) ProtoMessage()               {}
func (*MsgAuthEcho) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *MsgAuthEcho) GetLabel() string {
	if m != nil && m.Label != nil {
		return *m.Label
	}
	return ""
}

func (m *MsgAuthEcho) GetType() int32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *MsgAuthEcho) GetText() string {
	if m != nil && m.Text != nil {
		return *m.Text
	}
	return ""
}

func (m *MsgAuthEcho) GetReps() []int64 {
	if m != nil {
		return m.Reps
	}
	return nil
}

func (m *MsgAuthEcho) GetOptionalgroup() *MsgAuthEcho_OptionalGroup {
	if m != nil {
		return m.Optionalgroup
	}
	return nil
}

type MsgAuthEcho_OptionalGroup struct {
	RequiredField    *string `protobuf:"bytes,5,req,name=RequiredField,json=requiredField" json:"RequiredField,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MsgAuthEcho_OptionalGroup) Reset()                    { *m = MsgAuthEcho_OptionalGroup{} }
func (m *MsgAuthEcho_OptionalGroup) String() string            { return proto.CompactTextString(m) }
func (*MsgAuthEcho_OptionalGroup) ProtoMessage()               {}
func (*MsgAuthEcho_OptionalGroup) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2, 0} }

func (m *MsgAuthEcho_OptionalGroup) GetRequiredField() string {
	if m != nil && m.RequiredField != nil {
		return *m.RequiredField
	}
	return ""
}

func init() {
	proto.RegisterType((*MsgAuthClient)(nil), "system.msg_auth_client")
	proto.RegisterType((*MsgAuthClient_OptionalGroup)(nil), "system.msg_auth_client.OptionalGroup")
	proto.RegisterType((*MsgAuthServer)(nil), "system.msg_auth_server")
	proto.RegisterType((*MsgAuthServer_OptionalGroup)(nil), "system.msg_auth_server.OptionalGroup")
	proto.RegisterType((*MsgAuthEcho)(nil), "system.msg_auth_echo")
	proto.RegisterType((*MsgAuthEcho_OptionalGroup)(nil), "system.msg_auth_echo.OptionalGroup")
}

var fileDescriptor0 = []byte{
	// 236 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x29, 0xae, 0x2c, 0x2e,
	0x49, 0xcd, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x83, 0xf0, 0x94, 0x9e, 0x33, 0x72,
	0xf1, 0xe7, 0x16, 0xa7, 0xc7, 0x27, 0x96, 0x96, 0x64, 0xc4, 0x27, 0xe7, 0x64, 0xa6, 0xe6, 0x95,
	0x08, 0x89, 0x70, 0xb1, 0xe6, 0x24, 0x26, 0xa5, 0xe6, 0x48, 0x30, 0x2a, 0x30, 0x69, 0x70, 0x06,
	0x41, 0x38, 0x42, 0x42, 0x5c, 0x2c, 0x25, 0x95, 0x05, 0xa9, 0x12, 0x4c, 0x0a, 0x8c, 0x1a, 0xac,
	0x41, 0x60, 0x36, 0x58, 0x2c, 0xb5, 0xa2, 0x44, 0x82, 0x19, 0x28, 0xc6, 0x19, 0x04, 0x66, 0x83,
	0xc4, 0x8a, 0x52, 0x0b, 0x8a, 0x25, 0x58, 0x14, 0x98, 0x35, 0x98, 0x83, 0xc0, 0x6c, 0x21, 0x6f,
	0x2e, 0xde, 0xfc, 0x82, 0x92, 0xcc, 0xfc, 0xbc, 0xc4, 0x9c, 0xf4, 0xa2, 0xfc, 0xd2, 0x02, 0x09,
	0x56, 0xa0, 0x06, 0x2e, 0x23, 0x55, 0x3d, 0xa8, 0x9b, 0xd0, 0x5c, 0xa0, 0xe7, 0x0f, 0x55, 0xec,
	0x0e, 0x52, 0x1c, 0x84, 0xaa, 0x57, 0xca, 0x94, 0x8b, 0x17, 0x45, 0x5e, 0x48, 0x85, 0x8b, 0x37,
	0x28, 0xb5, 0xb0, 0x34, 0xb3, 0x28, 0x35, 0xc5, 0x2d, 0x33, 0x35, 0x27, 0x05, 0x68, 0x3a, 0xc8,
	0xdd, 0xbc, 0x45, 0xc8, 0x82, 0xa8, 0x3e, 0x2d, 0x4e, 0x2d, 0x2a, 0x4b, 0x2d, 0x1a, 0x48, 0x9f,
	0x42, 0x5c, 0x40, 0x13, 0x9f, 0x3e, 0x66, 0xe4, 0xe2, 0x85, 0xdb, 0x93, 0x9a, 0x9c, 0x91, 0x4f,
	0x03, 0x7f, 0x7a, 0x62, 0xf7, 0xa7, 0x32, 0x86, 0x3f, 0x41, 0xf6, 0xd3, 0xc2, 0x97, 0x80, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x9a, 0x00, 0xbe, 0x28, 0xd0, 0x02, 0x00, 0x00,
}
