// Code generated by protoc-gen-go.
// source: test.proto
// DO NOT EDIT!

/*
Package test is a generated protocol buffer package.

It is generated from these files:
	test.proto

It has these top-level messages:
	MsgTest
*/
package test

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type Proto int32

const (
	Proto_id Proto = 2
)

var Proto_name = map[int32]string{
	2: "id",
}
var Proto_value = map[string]int32{
	"id": 2,
}

func (x Proto) Enum() *Proto {
	p := new(Proto)
	*p = x
	return p
}
func (x Proto) String() string {
	return proto.EnumName(Proto_name, int32(x))
}
func (x *Proto) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Proto_value, data, "Proto")
	if err != nil {
		return err
	}
	*x = Proto(value)
	return nil
}
func (Proto) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type MsgTest struct {
	ProtoId          *Proto  `protobuf:"varint,1,req,name=proto_id,json=protoId,enum=test.Proto,def=2" json:"proto_id,omitempty"`
	MsgId            *uint32 `protobuf:"varint,2,req,name=msg_id,json=msgId,def=1" json:"msg_id,omitempty"`
	Text             *string `protobuf:"bytes,3,opt,name=text" json:"text,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MsgTest) Reset()                    { *m = MsgTest{} }
func (m *MsgTest) String() string            { return proto.CompactTextString(m) }
func (*MsgTest) ProtoMessage()               {}
func (*MsgTest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

const Default_MsgTest_ProtoId Proto = Proto_id
const Default_MsgTest_MsgId uint32 = 1

func (m *MsgTest) GetProtoId() Proto {
	if m != nil && m.ProtoId != nil {
		return *m.ProtoId
	}
	return Default_MsgTest_ProtoId
}

func (m *MsgTest) GetMsgId() uint32 {
	if m != nil && m.MsgId != nil {
		return *m.MsgId
	}
	return Default_MsgTest_MsgId
}

func (m *MsgTest) GetText() string {
	if m != nil && m.Text != nil {
		return *m.Text
	}
	return ""
}

func init() {
	proto.RegisterType((*MsgTest)(nil), "test.msg_test")
	proto.RegisterEnum("test.Proto", Proto_name, Proto_value)
}

var fileDescriptor0 = []byte{
	// 127 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0x49, 0x2d, 0x2e,
	0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x01, 0xb1, 0x95, 0x52, 0xb8, 0x38, 0x72, 0x8b,
	0xd3, 0xe3, 0x41, 0x6c, 0x21, 0x2d, 0x2e, 0x0e, 0xb0, 0x54, 0x7c, 0x66, 0x8a, 0x04, 0xa3, 0x02,
	0x93, 0x06, 0x9f, 0x11, 0xb7, 0x1e, 0x42, 0x83, 0x15, 0x53, 0x66, 0x4a, 0x10, 0x3b, 0x98, 0xe9,
	0x99, 0x22, 0x24, 0xc1, 0xc5, 0x06, 0xd2, 0x07, 0x54, 0xc9, 0x04, 0x54, 0xc9, 0x6b, 0xc5, 0x68,
	0x18, 0xc4, 0x0a, 0x14, 0x00, 0xca, 0x08, 0x71, 0x01, 0x4d, 0xae, 0x28, 0x91, 0x60, 0x56, 0x60,
	0xd4, 0xe0, 0x0c, 0x02, 0xb3, 0xb5, 0xf8, 0xb9, 0x58, 0x21, 0x96, 0xb2, 0x71, 0x01, 0x4d, 0x11,
	0x60, 0x02, 0x04, 0x00, 0x00, 0xff, 0xff, 0x30, 0xd3, 0x1d, 0x5f, 0x89, 0x00, 0x00, 0x00,
}
