// Code generated by protoc-gen-go.
// source: system.proto
// DO NOT EDIT!

/*
Package system is a generated protocol buffer package.

It is generated from these files:
	system.proto

It has these top-level messages:
	MsgAuthClient
	MsgAuthServer
	MsgEcho
*/
package system

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type Proto int32

const (
	Proto_id Proto = 1
)

var Proto_name = map[int32]string{
	1: "id",
}
var Proto_value = map[string]int32{
	"id": 1,
}

func (x Proto) Enum() *Proto {
	p := new(Proto)
	*p = x
	return p
}
func (x Proto) String() string {
	return proto.EnumName(Proto_name, int32(x))
}
func (x *Proto) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Proto_value, data, "Proto")
	if err != nil {
		return err
	}
	*x = Proto(value)
	return nil
}
func (Proto) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type MsgAuthClient struct {
	MsgId            *uint32                      `protobuf:"varint,1,req,name=msg_id,json=msgId,def=1" json:"msg_id,omitempty"`
	Type             *int32                       `protobuf:"varint,2,opt,name=type" json:"type,omitempty"`
	Text             *string                      `protobuf:"bytes,3,opt,name=text" json:"text,omitempty"`
	Reps             []int64                      `protobuf:"varint,4,rep,name=reps" json:"reps,omitempty"`
	Optionalgroup    *MsgAuthClient_OptionalGroup `protobuf:"group,5,opt,name=OptionalGroup,json=optionalgroup" json:"optionalgroup,omitempty"`
	XXX_unrecognized []byte                       `json:"-"`
}

func (m *MsgAuthClient) Reset()                    { *m = MsgAuthClient{} }
func (m *MsgAuthClient) String() string            { return proto.CompactTextString(m) }
func (*MsgAuthClient) ProtoMessage()               {}
func (*MsgAuthClient) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

const Default_MsgAuthClient_MsgId uint32 = 1

func (m *MsgAuthClient) GetMsgId() uint32 {
	if m != nil && m.MsgId != nil {
		return *m.MsgId
	}
	return Default_MsgAuthClient_MsgId
}

func (m *MsgAuthClient) GetType() int32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *MsgAuthClient) GetText() string {
	if m != nil && m.Text != nil {
		return *m.Text
	}
	return ""
}

func (m *MsgAuthClient) GetReps() []int64 {
	if m != nil {
		return m.Reps
	}
	return nil
}

func (m *MsgAuthClient) GetOptionalgroup() *MsgAuthClient_OptionalGroup {
	if m != nil {
		return m.Optionalgroup
	}
	return nil
}

type MsgAuthClient_OptionalGroup struct {
	RequiredField    *string `protobuf:"bytes,6,req,name=RequiredField,json=requiredField" json:"RequiredField,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MsgAuthClient_OptionalGroup) Reset()                    { *m = MsgAuthClient_OptionalGroup{} }
func (m *MsgAuthClient_OptionalGroup) String() string            { return proto.CompactTextString(m) }
func (*MsgAuthClient_OptionalGroup) ProtoMessage()               {}
func (*MsgAuthClient_OptionalGroup) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

func (m *MsgAuthClient_OptionalGroup) GetRequiredField() string {
	if m != nil && m.RequiredField != nil {
		return *m.RequiredField
	}
	return ""
}

type MsgAuthServer struct {
	MsgId            *uint32 `protobuf:"varint,1,req,name=msg_id,json=msgId,def=2" json:"msg_id,omitempty"`
	SvrId            *uint32 `protobuf:"varint,2,req,name=svr_id,json=svrId" json:"svr_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MsgAuthServer) Reset()                    { *m = MsgAuthServer{} }
func (m *MsgAuthServer) String() string            { return proto.CompactTextString(m) }
func (*MsgAuthServer) ProtoMessage()               {}
func (*MsgAuthServer) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

const Default_MsgAuthServer_MsgId uint32 = 2

func (m *MsgAuthServer) GetMsgId() uint32 {
	if m != nil && m.MsgId != nil {
		return *m.MsgId
	}
	return Default_MsgAuthServer_MsgId
}

func (m *MsgAuthServer) GetSvrId() uint32 {
	if m != nil && m.SvrId != nil {
		return *m.SvrId
	}
	return 0
}

type MsgEcho struct {
	MsgId            *uint32 `protobuf:"varint,1,req,name=msg_id,json=msgId,def=3" json:"msg_id,omitempty"`
	Text             *string `protobuf:"bytes,2,opt,name=text" json:"text,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MsgEcho) Reset()                    { *m = MsgEcho{} }
func (m *MsgEcho) String() string            { return proto.CompactTextString(m) }
func (*MsgEcho) ProtoMessage()               {}
func (*MsgEcho) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

const Default_MsgEcho_MsgId uint32 = 3

func (m *MsgEcho) GetMsgId() uint32 {
	if m != nil && m.MsgId != nil {
		return *m.MsgId
	}
	return Default_MsgEcho_MsgId
}

func (m *MsgEcho) GetText() string {
	if m != nil && m.Text != nil {
		return *m.Text
	}
	return ""
}

func init() {
	proto.RegisterType((*MsgAuthClient)(nil), "system.msg_auth_client")
	proto.RegisterType((*MsgAuthClient_OptionalGroup)(nil), "system.msg_auth_client.OptionalGroup")
	proto.RegisterType((*MsgAuthServer)(nil), "system.msg_auth_server")
	proto.RegisterType((*MsgEcho)(nil), "system.msg_echo")
	proto.RegisterEnum("system.Proto", Proto_name, Proto_value)
}

var fileDescriptor0 = []byte{
	// 262 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x64, 0x90, 0x41, 0x4b, 0x03, 0x31,
	0x10, 0x85, 0xd9, 0xb4, 0x59, 0xec, 0x60, 0xa8, 0x04, 0x84, 0xe0, 0x69, 0x59, 0x14, 0x16, 0x0f,
	0x0b, 0x56, 0x04, 0xf1, 0xe8, 0x41, 0x29, 0x1e, 0x84, 0xfc, 0x81, 0x52, 0x9a, 0xa1, 0x0d, 0x6c,
	0x9b, 0x98, 0x64, 0x8b, 0xfd, 0xcd, 0xfe, 0x09, 0x93, 0x75, 0xc5, 0xad, 0xbd, 0xcd, 0x7c, 0x33,
	0x0f, 0xde, 0x7b, 0x70, 0xee, 0x0f, 0x3e, 0xe0, 0xb6, 0xb6, 0xce, 0x04, 0xc3, 0xf3, 0x9f, 0xad,
	0xfc, 0xca, 0x60, 0xba, 0xf5, 0xeb, 0xc5, 0xb2, 0x0d, 0x9b, 0xc5, 0xaa, 0xd1, 0xb8, 0x0b, 0x5c,
	0x40, 0x9e, 0x90, 0x56, 0x22, 0x2b, 0x48, 0xc5, 0x9e, 0xb2, 0x3b, 0x49, 0x23, 0x98, 0x2b, 0xce,
	0x61, 0x1c, 0x0e, 0x16, 0x05, 0x29, 0xb2, 0x8a, 0xca, 0x6e, 0xee, 0x18, 0x7e, 0x06, 0x31, 0x8a,
	0x6c, 0x22, 0xbb, 0x39, 0x31, 0x87, 0xd6, 0x8b, 0x71, 0x31, 0xaa, 0x46, 0xb2, 0x9b, 0xf9, 0x1b,
	0x30, 0x63, 0x83, 0x36, 0xbb, 0x65, 0xb3, 0x76, 0xa6, 0xb5, 0x82, 0x46, 0x01, 0xcc, 0x6e, 0xea,
	0xde, 0xd7, 0x3f, 0x17, 0xf5, 0x7b, 0xff, 0xfc, 0x9a, 0x9e, 0xe5, 0xb1, 0xf6, 0xea, 0x01, 0xd8,
	0xd1, 0x9d, 0x5f, 0x03, 0x93, 0xf8, 0xd1, 0x6a, 0x87, 0xea, 0x45, 0x63, 0xa3, 0x44, 0x1e, 0xad,
	0x4f, 0x24, 0x73, 0x43, 0x58, 0x3e, 0x0f, 0xc2, 0x7a, 0x74, 0x7b, 0x74, 0xa7, 0x61, 0x67, 0xbf,
	0x61, 0x2f, 0x21, 0xf7, 0x7b, 0x97, 0x2e, 0x24, 0x5d, 0x24, 0x8d, 0xdb, 0x5c, 0x95, 0x8f, 0x70,
	0x96, 0x04, 0xb8, 0xda, 0x98, 0x53, 0xf1, 0xfd, 0xb0, 0xa9, 0xd4, 0x0a, 0xf9, 0x6b, 0xe5, 0x76,
	0x0a, 0xb4, 0x2f, 0x1f, 0x88, 0x56, 0x17, 0xd9, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0x91, 0x2d,
	0x95, 0x75, 0x93, 0x01, 0x00, 0x00,
}
